FROM code-container-packages:latest

RUN curl -fsSL https://claude.ai/install.sh | bash
RUN echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc

RUN npm install -g opencode-ai

RUN npm install -g @openai/codex

RUN npm install -g @google/gemini-cli

RUN npm install -g @github/copilot
